
import { GoogleGenAI } from "@google/genai";
import { GeneratedImage } from "../types";

export const generateIcon = async (prompt: string): Promise<GeneratedImage> => {
  // STRICT REQUIREMENT: Access API key from process.env.API_KEY
  const apiKey = process.env.API_KEY;
  
  if (!apiKey) {
    throw new Error("System configuration error: API Key is missing from environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Use gemini-2.5-flash-image for general image generation tasks as per guidelines
  const model = 'gemini-2.5-flash-image';
  
  try {
    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          {
            text: `Generate a high-quality, professional, centered app icon for: ${prompt}. Minimalist, vector style, white background, suitable for a computer icon.`,
          },
        ],
      },
    });

    let generatedImage: GeneratedImage | null = null;

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           generatedImage = {
             base64: part.inlineData.data,
             mimeType: part.inlineData.mimeType || 'image/png',
             url: `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`
           };
           break;
        }
      }
    }

    if (!generatedImage) {
      throw new Error("No image was generated by the Gemini model.");
    }

    return generatedImage;

  } catch (error: any) {
    console.error("Gemini Image Generation Error:", error);
    throw new Error(error.message || "Failed to generate icon with Gemini.");
  }
};
